<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.3"/>
    <xacro:property name="base_width" value="0.1702"/>
    <xacro:property name="base_height" value="0.115"/>
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_length" value="0.0374"/>

    <xacro:property name="laser_dia" value="0.0556"/>
    <xacro:property name="laser_hgt" value="0.0413"/>
    <xacro:property name="laser_mass" value="0.11"/>

    <!-- Compute inertia for a solid cylinder about center -->
    <xacro:property name="laser_ixx"
                    value="${(1.0/12.0) * laser_mass * (3*((laser_dia/2)* (laser_dia/2)) + laser_hgt * laser_hgt)}"/>
    <xacro:property name="laser_iyy" value="${laser_ixx}"/>
    <xacro:property name="laser_izz"
                    value="${0.5 * laser_mass * ((laser_dia/2) * (laser_dia/2))}"/>


    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/ 2.0}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/ 2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="2.02" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height/ 2.0}" o_rpy="0 0 0"/>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="0.1185" r="${wheel_radius}" l="${wheel_length}"
                                    o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right_rear"/>
    <xacro:wheel_link prefix="left_rear"/>
    <xacro:wheel_link prefix="right_front"/>
    <xacro:wheel_link prefix="left_front"/>

    <link name="laser_frame">
        <!-- Inertial -->
        <inertial>
            <mass value="${laser_mass}"/>                 <!-- kg -->
            <inertia
                    ixx="${laser_ixx}"
                    iyy="${laser_iyy}"
                    izz="${laser_izz}"
                    ixy="0.0" ixz="0.0" iyz="0.0"/>
        </inertial>

        <!-- Visual -->
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder
                        length="${laser_hgt}"
                        radius="${laser_dia/2}"/>
            </geometry>
            <material name="laser_red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>

        <!-- Collision (same shape as visual) -->
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder
                        length="${laser_hgt}"
                        radius="${laser_dia/2}"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_rear_wheel_link"/>
        <origin xyz="${-base_length / 2.5} ${-(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_rear_wheel_link"/>
        <origin xyz="${-base_length / 2.5} ${(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel_link"/>
        <origin xyz="${base_length / 2.5} ${(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_right_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_front_wheel_link"/>
        <origin xyz="${base_length / 2.5} ${-(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="laser_mount" type="fixed">
        <parent link="base_link"/>
        <child  link="laser_frame"/>
        <origin xyz="0.12 0 ${(base_height + (0.0413/2.0))}" rpy="3.1416 0  0"/>
    </joint>

</robot>